# Generated by Django 3.2.2 on 2021-06-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
