# Generated by Django 3.2.2 on 2021-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210602_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addons',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
