# Generated by Django 3.2.2 on 2021-06-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210603_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=100)),
                ('addons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.addons')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
