# Generated by Django 3.2.2 on 2021-06-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.CharField(max_length=200)),
                ('image_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('image_type', models.IntegerField(choices=[(1, 'Image'), (2, 'Portrait/Headshot/Model'), (3, 'Others')], default=1)),
                ('save_metadata', models.BooleanField(default=False)),
                ('addons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.addons')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
