# Generated by Django 3.2.2 on 2021-06-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_clipping_path',
            field=models.BooleanField(default=False),
        ),
    ]
