# Generated by Django 3.2.2 on 2021-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_order_need_clipping_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addons',
            name='is_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_product',
            field=models.BooleanField(default=False),
        ),
    ]
