# Generated by Django 3.2.2 on 2021-06-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210627_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='order',
            name='requirements',
        ),
    ]
