# Generated by Django 3.2.2 on 2021-06-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210627_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addon',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='requirement',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
