# Generated by Django 3.2.2 on 2021-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210627_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='job_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
