# Generated by Django 3.2.2 on 2021-06-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_order_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
