# Generated by Django 3.2.2 on 2021-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.CharField(max_length=200)),
                ('image_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('image_type', models.IntegerField(choices=[(1, 'Image'), (2, 'Portrait/Headshot/Model'), (3, 'Others')], default=1)),
                ('job_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('need_clipping_path', models.BooleanField(default=False)),
                ('save_metadata', models.BooleanField(default=False)),
                ('requirement', models.JSONField(blank=True, default=None, null=True)),
                ('addon', models.JSONField(blank=True, default=None, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
